name: Python Autorun

on:
  push:
    branches: [ "main", "test_func"]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:
  
permissions: write-all

jobs:
  get_data:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install httpx bs4 pydantic
    - name: Run Scripts
      run: sh autorun.sh
    - name: GitHub Push
      # You may pin to the exact commit or the version.
      # uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
      uses: ad-m/github-push-action@v0.6.0
      with:
        # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: ${{ secrets.TOKEN }}
        # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
        repository: ACGN-Alliance/AZbot-data # optional, default is 
        # Destination branch to push changes
        # Determines if force push is used
        force: true # optional
        # Determines if --tags is used
        # Directory to change to before pushing.
        directory: "./data" # optional, default is .
