name: Python Autorun

on:
  push:
    branches: [ "main", "test_func"]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:
  
permissions: write-all

jobs:
  get_data:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install httpx bs4 pydantic
    - name: Run Scripts
      run: sh autorun.sh
      # You may pin to the exact commit or the version.
      # uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
    - name: Push git subdirectory as branch
      # You may pin to the exact commit or the version.
      # uses: s0/git-publish-subdir-action@92faf786f11dfa44fc366ac3eb274d193ca1af7e
      uses: s0/git-publish-subdir-action@v2.6.0
      env:
        REPO: self
        BRANCH: data
        FOLDER: data
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
