name: Python Autorun

on:
  push:
    branches: [ "main", "test_func"]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

permissions: write-all

jobs:
  get_data:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install httpx bs4 pydantic
    - name: Run Scripts
      run: sh autorun.sh
    - name: Push to another repository
      # You may pin to the exact commit or the version.
      # uses: kevocde/github-action-push-to-another-repository@e015a867ff2f9cc5e8e0302f0ac70631d261d983
      uses: kevocde/github-action-push-to-another-repository@v0.1.1
      with:
        # Target repository URI
        repository-uri: https://github.com/MRSlouzk/AZbot-data.git
        # Target repository username
        username: github-actions[bot]
        # Target repository token or password
        token: ${{ secrets.TOKEN }}
        # Target repository branch
        branch: master
