name: Python Autorun

on:
  push:
    branches: [ "main", "test_func"]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

permissions: write-all

jobs:
  get_data:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install httpx bs4 pydantic pil-utils
    - name: Run Scripts
      run: sh autorun.sh
    - name: Commit
      run: |
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        git commit -m "Update data" -a || exit 0
        git push